v2.0

diff --git a/queryibooks b/queryibooks
--- a/queryibooks
+++ b/queryibooks
@@ -1,98 +1,97 @@
 #!/usr/bin/env bash
-# Author: Annie Tran https://github.com/nntrn
+# shellcheck disable=SC2034,SC1090
+# Author: https://github.com/nntrn
 # Repository: https://github.com/nntrn/queryibooks
 
 set -e
 
-PROG=$(basename $0)
-VERSION=1.0
-SCRIPT=$(realpath $0)
-DIR=$(dirname $SCRIPT)
-NOW=$(date +%s)
-PROG_HOME=$HOME/.queryibooks
-CACHEDIR=$PROG_HOME/.cache/$(date +%F)
-LOGFILE=$PROG_HOME/.cache/logs.txt
+PROG=queryibooks
+VERSION=2.0
 
-QUERYIBOOKS_HTML_TEMPLATE=$DIR/templates/index.html
-QUERYIBOOKS_TIME=3600
-QUERYIBOOKS_DEBUGGER_ON=
-QUERYIBOOKS_FORCE=
-QUERYIBOOKS_PRINT=
-QUERYIBOOKS_OUT=$CACHEDIR
+USER_IBOOKS=$HOME/Library/Containers/com.apple.iBooksX
+QUERYIBOOKS_HOME="$HOME/.cache/queryibooks"
 
-DB_BASE=$HOME/Library/Containers/com.apple.iBooksX
-DB_ANNOTATIONS=$(ls -1 $DB_BASE/Data/Documents/AEAnnotation/*.sqlite)
-SQL_ANNOTATIONS='select * from ZAEANNOTATION where ZANNOTATIONSELECTEDTEXT IS NOT NULL;'
-DB_ASSETS=$(ls -1 $DB_BASE/Data/Documents/BKLibrary/*.sqlite)
-SQL_ASSETS='select * from ZBKLIBRARYASSET order by ZPURCHASEDATE desc;'
+mkdir -p $QUERYIBOOKS_HOME
 
-_echo() {
-  [[ ! -d $PROG_HOME ]] && mkdir -p $PROG_HOME
-  if [[ -n $QUERYIBOOKS_DEBUGGER_ON ]]; then
-    echo "$(date +'[%c]') $*" | tee -a $LOGFILE
-  else
-    echo "$(date +'[%c]') $*" >>$LOGFILE
-  fi
-}
+declare -A db_annotations
+db_annotations[name]=annotations
+db_annotations[path]="$(ls -1 $USER_IBOOKS/Data/Documents/AEAnnotation/*.sqlite)"
+db_annotations[sql]="select * from ZAEANNOTATION
+where ZANNOTATIONSELECTEDTEXT IS NOT NULL
+and ZANNOTATIONSELECTEDTEXT <> ''
+and ZANNOTATIONDELETED = 0;"
 
-wal_checkpoint() {
-  DB="$1"
-  if [[ -f $DB-wal ]]; then
-    MOD_DB=$(stat -f %m $DB)
-    MOD_WALDB=$(stat -f %m $DB-wal)
-    if [[ $MOD_DB -lt $MOD_WALDB ]]; then
-      _echo "Updating database: $DB"
-      sqlite3 $DB 'pragma wal_checkpoint;' >/dev/null
-    fi
-  fi
-}
+declare -A db_assets
+db_assets[name]=assets
+db_assets[path]="$(ls -1 $USER_IBOOKS/Data/Documents/BKLibrary/*.sqlite)"
+db_assets[sql]="select * from ZBKLIBRARYASSET;"
 
-get_var() {
-  echo "${!1}"
-}
+HELP_TEXT='
+Tool for extracting iBooks annotations
 
-query_db() {
-  TABLE=$1
-  OUTFILE=$QUERYIBOOKS_OUT/${TABLE,,}.json
-  TIMEDIFF=0
-  DB=$(get_var DB_${TABLE})
-  SQL="$(get_var SQL_${TABLE})"
+Usage:
+  queryibooks [-f|--force] [-w|--write-to] [-c|--max-cache-age]
+  queryibooks [-h|--help] [-v|--version]
 
-  mkdir -p $CACHEDIR
+Options:
+  -f, --force             Run database update regardless of cache age
+  -w, --write-to          Where to write output to
+  -c, --use-cache         Use data from last run
+  -c, --max-cache-age
+  -h, --help
+  -v, --version
 
-  if [[ -f $OUTFILE ]]; then
-    LAST_MOD=$(stat -f %m $OUTFILE)
-    TIMEDIFF=$((NOW - LAST_MOD))
-  fi
+Environment:
+  QUERYIBOOKS_FORCE=1           # same as --force
+  QUERYIBOOKS_USECACHE=1        # same as --use-cache
+  QUERYIBOOKS_OUTPUT=<FILEPATH>
+  QUERYIBOOKS_MAX_CACHE=<minutes>
+'
 
-  [[ $TIMEDIFF -gt $QUERYIBOOKS_TIME ]] && QUERYIBOOKS_FORCE=1
+JQ_FUNC='
+  def map_annotations: {
+    Z_PK,
+    ZANNOTATIONCREATIONDATE,
+    ZANNOTATIONASSETID,
+    ZANNOTATIONSELECTEDTEXT,
+    ZFUTUREPROOFING5,
+    ZANNOTATIONNOTE,
+    ZPLLOCATIONRANGESTART,
+    ZANNOTATIONSTYLE,
+    ZANNOTATIONTYPE,
+    ZANNOTATIONISUNDERLINE
+  };
 
-  if [[ ! -f $OUTFILE ]] || [[ -n $QUERYIBOOKS_FORCE ]]; then
-    wal_checkpoint "$DB"
-    _echo "Saving $OUTFILE"
-    sqlite3 -json "$DB" "$SQL" ".exit" >$OUTFILE
-  else
-    _echo "Using $OUTFILE (Created ${TIMEDIFF}s ago)"
-  fi
-}
+  def map_assets:
+    { ZASSETID, ZTITLE, ZAUTHOR, ZGENRE, ZSTOREID, ZSORTTITLE, ZASSETGUID };
 
-create_annotations_html() {
-  if [[ -f $1 ]] && [[ -f $QUERYIBOOKS_HTML_TEMPLATE ]]; then
-    cat $QUERYIBOOKS_HTML_TEMPLATE | sed '/^.*<script id="annotations"/q'
-    cat $1 | jq -c | sed 's|},{|},\n  {|g'
-    cat $QUERYIBOOKS_HTML_TEMPLATE | sed -n '/<!--/,/<\/script/p'
-  else
-    return 1
-  fi
-}
+  def map_json:
+    reduce inputs as $s (.; .[input_filename|gsub(".json";"")|split("/")|last|ascii_downcase] += $s);
 
-main() {
-  mkdir -p $QUERYIBOOKS_OUT
-  query_db ANNOTATIONS
-  query_db ASSETS
+  def join_assets:
+    INDEX(
+      .assets[]; .ZASSETID) as $c
+      | .annotations
+      | map((map_annotations)+($c[.ZANNOTATIONASSETID]|map_assets)
+    );
 
-  jq -n -L $DIR/.jq 'include "queryibooks"; ibooks_data' $QUERYIBOOKS_OUT/{assets,annotations}.json >$QUERYIBOOKS_OUT/data.json
-  create_annotations_html $QUERYIBOOKS_OUT/data.json >$QUERYIBOOKS_OUT/annotations.html
+  def convertmacostime:
+    map(
+      with_entries(
+        .key as $k|.value |= (
+        if ($k|contains("DATE"))
+        then ((.// 0) +978307200|strflocaltime("%FT%TZ"))
+        else .
+        end)
+      )
+    );
+
+  def build: map_json|join_assets|convertmacostime;
+'
+
+_usage() {
+  echo "$HELP_TEXT"
+  exit 1
 }
 
 _version() {
@@ -100,46 +99,82 @@ _version() {
   exit 0
 }
 
-_usage() {
-  echo "
-Tool for extracting asset and annotation data from ibooks
+log() {
+  echo -e "$(date +'%F %X') $*" >>${QUERYIBOOKS_HOME}/log.txt
+}
 
-Usage:
-  $PROG [OPTIONS]
+sync_database() {
+  local DB="$1"
+  if [[ -f $DB-wal ]]; then
+    MOD_DB=$(stat -f %m "$DB")
+    MOD_WALDB=$(stat -f %m "$DB-wal")
+    if [[ $MOD_DB -lt $MOD_WALDB ]]; then
+      sqlite3 "$DB" 'pragma wal_checkpoint;' ".exit" >/dev/null
+      log "Sync ${DB##*/} $MOD_DB -> $(stat -f %m "$DB")"
+      echo 1
+    fi
+  fi
+}
 
-Options:
-  -h, --help
-  -v, --version
-  -f, --force                 [QUERYIBOOKS_FORCE]
-  -o, --out <DIR>             [QUERYIBOOKS_OUT]
-  -r, --recheck <SECS>        [QUERYIBOOKS_TIME] (Default: 3600)
-  -p, --print <FILENAME>      [QUERYIBOOKS_PRINT]
-  --html-template <FILEPATH>  [QUERYIBOOKS_HTML_TEMPLATE]
-"
-  exit 1
+querydata() {
+  local -n data=$1
+
+  TABLE="${data[name]}"
+  DB_PATH="${data[path]}"
+  SQL="${data[sql]}"
+  SAVEFILE="${QUERYIBOOKS_CACHE}/${TABLE}.json"
+
+  if [[ $QUERYIBOOKS_USECACHE -eq 1 ]]; then
+    QUERYIBOOKS_FORCE=
+  else
+    QUERYIBOOKS_FORCE=$(sync_database "$DB_PATH")
+  fi
+
+  [[ ! -f $SAVEFILE ]] && QUERYIBOOKS_FORCE=1
+
+  if [[ $QUERYIBOOKS_FORCE -eq 1 ]]; then
+    sqlite3 -json "$DB_PATH" "$SQL" ".exit" >$SAVEFILE
+    log "Fetch updated data from ${DB_PATH##*/}"
+  fi
 }
 
 for i in "$@"; do
   case $i in
   -h | --help) _usage ;;
   -v | --version) _version ;;
-  -p | --print) QUERYIBOOKS_PRINT=$2 && shift 2 ;;
   -f | --force) QUERYIBOOKS_FORCE=1 && shift ;;
-  -o | --out) QUERYIBOOKS_OUT=$2 && shift 2 ;;
-  -r | --recheck) QUERYIBOOKS_TIME=$2 && shift 2 ;;
-  --html-template) QUERYIBOOKS_HTML_TEMPLATE="$2" && shift 2 ;;
+  -w | --write-to) QUERYIBOOKS_OUTPUT=$2 && shift 2 ;;
+  -c | --use-cache) QUERYIBOOKS_USECACHE=1 && shift ;;
   esac
 done
 
-main "$@" 1>/dev/null
-
-if [[ -n $QUERYIBOOKS_PRINT ]]; then
-  _PRINTFILE=$(ls -1 $QUERYIBOOKS_OUT/${QUERYIBOOKS_PRINT}*)
-  if [[ -f $_PRINTFILE ]]; then
-    cat $_PRINTFILE
-  else
-    echo "Error $_PRINTFILE"
-  fi
-else
-  find $QUERYIBOOKS_OUT -type f -name "*.json" -exec realpath {} \;
+if ! command -v jq &>/dev/null; then
+  echo "Download jq before continuing.. Aborting"
+  exit 1
 fi
+
+QUERYIBOOKS_ENV=$QUERYIBOOKS_HOME/.env
+QUERYIBOOKS_CACHE="$QUERYIBOOKS_HOME"
+
+if [[ $QUERYIBOOKS_USECACHE -eq 1 ]] && [[ -f $QUERYIBOOKS_ENV ]]; then
+  source $QUERYIBOOKS_ENV
+  log "QUERYIBOOKS_ENV=$QUERYIBOOKS_ENV"
+else
+  TODAY="$(date +%F-%H)"
+  QUERYIBOOKS_CACHE="$QUERYIBOOKS_HOME/$TODAY"
+  mkdir -p $QUERYIBOOKS_CACHE
+fi
+
+querydata db_assets
+querydata db_annotations
+
+jq -n "$JQ_FUNC build" ${QUERYIBOOKS_CACHE}/{assets,annotations}.json >$QUERYIBOOKS_CACHE/ibooks.json
+
+if [[ -n $QUERYIBOOKS_OUTPUT ]]; then
+  cp "$QUERYIBOOKS_CACHE/ibooks.json" "$QUERYIBOOKS_OUTPUT"
+  echo "Saved to $QUERYIBOOKS_OUTPUT"
+else
+  cat $QUERYIBOOKS_CACHE/ibooks.json
+fi
+
+echo "QUERYIBOOKS_CACHE=$QUERYIBOOKS_CACHE" >$QUERYIBOOKS_ENV
